kind: pipeline
name: Check

platform:
  arch: amd64
  os: linux

steps:
  # Install all of our dependencies so that they're
  # available for future steps
  - name: Install dependencies
    image: node:18-alpine
    commands:
      - yarn

  - name: Lint
    image: node:18-alpine
    commands:
      - yarn check:lint

  - name: Format
    image: node:18-alpine
    commands:
      - yarn check:format

  - name: Types
    image: node:18-alpine
    commands:
      - yarn check:types

trigger:
  event:
    # Running on push will ensure that code is
    # checked on PRs _and_ on commits to the default
    # branch
    - push
