changesetIgnorePatterns:
  - "**/*.{test}.{js,ts,jsx,tsx}"
  - "!(src/**/*|package.json|.swcrc*)"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
